module.exports =
	options:
		cwd:"../views/md"
	router:
		"quick-start":
			title:"快速入门"
			file:"quick-start.md"
		"tutorial-todo":
			title:"实例教程——代办事项"
			file:"tutorial-todo.md"
		"code-guide":
			title:"Html页面规范"
			file:"code-guide.md"
		"faq":
			title:"FAQ"
			file:"faq.md"
		"model":
			title:"Model(视图模型)"
			file:"model.md"
		"data-model":
			title:"数据相关概念"
			file:"data-model.md"
		"expression":
			title:"表达式"
			file:"expression.md"
		"dom-directives":
			title:"DOM指令"
			file:"dom-directives.md"
		"element":
			title:"Element"
			file:"element.md"
		"action":
			title:"Action(动作)"
			file:"action.md"
		"router":
			title:"router(路由)"
			file:"router.md"
		"resource":
			title:"国际化"
			file:"resource.md"
		"definitions":
			title:"常用名词或规范"
			file:"definitions.md"
		"shell-tutorial":
			title:"Cola Shell总体介绍"
			file:"shell/tutorial.md"
		"shell-project":
			title:"创建App项目"
			file:"shell/project.md"
		"shell-setting":
			title:"基本参数设定"
			file:"shell/setting.md"
		"shell-router":
			title:"频道和卡片"
			file:"shell/router.md"
		"shell-service":
			title:"频道和卡片"
			file:"shell/service.md"
